#! /bin/bash

sbatch exps/69_warmup1_burnout20_td_c0.0_select_baselines_chi_square_wmt.sh
sbatch exps/70_warmup20_burnout20_td_c0.0_select_baselines_chi_square_wmt.sh
sbatch exps/71_sample_warmup1_burnout20_td_c0.0_select_baselines_chi_square_wmt.sh
sbatch exps/72_sample_warmup20_burnout20_td_c0.0_select_baselines_chi_square_wmt.sh